// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomLetterDuel.DAL.Data;

#nullable disable

namespace RandomLetterDuel.DAL.Migrations
{
    [DbContext(typeof(RandomLetterDuelDbContext))]
    partial class RandomLetterDuelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RandomLetterDuel.DAL.Entities.GameRoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentTurnPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequiredLetter")
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("UsedWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("RandomLetterDuel.DAL.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameRoomEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomEntityId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RandomLetterDuel.DAL.Entities.PlayerEntity", b =>
                {
                    b.HasOne("RandomLetterDuel.DAL.Entities.GameRoomEntity", null)
                        .WithMany("Players")
                        .HasForeignKey("GameRoomEntityId");
                });

            modelBuilder.Entity("RandomLetterDuel.DAL.Entities.GameRoomEntity", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
