<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RandomLetterDuel.DAL\RandomLetterDuel.DAL.csproj" />
    <ProjectReference Include="..\RandomLetterDuel.DTO\RandomLetterDuel.DTO.csproj" />
  </ItemGroup>

</Project>
